const supertest = require('supertest');
const chai = require('chai');
const chaiHttp = require('chai-http');
const expect = chai.expect;
const app = require('../src/modules/app/app.module.js');


console.log("Test suit 1");
app.set('trust proxy', false);
chai.use(chaiHttp);

describe('Contacts API', function() {
  let authToken;
  let randomeContact;
  let randomeContact_2;

  before(function(done) {
    this.timeout(10000);  // Set a timeout for async operations
    supertest(app)
      .post('/v1/auth/admin-login')
      .send({ email: 'admin@sesa1.com', password: 'password1' })
      .end((err, res) => {
        authToken = res.body.tokens.access.token;
        // console.log(">>>> ", authToken);
        done();
      });
  });

  it('should create a contact', function(done) {
    const contactData = {
      name: "Hend Isleem",
      phoneNumber: "123-456-0000",
      contactEmail: "Hend@example.com",
      subject: "Inquiry",
      message: "Hello, I am a contact generated by the test :)"
    };
    supertest(app)
      .post('/v1/contacts')
      .set('Authorization', `Bearer ${authToken}`)
      .send(contactData)
      .expect(204)
      .end((err, res) => {
        expect(res.status).to.equal(204);
        done();
      });
  });

  it('should retrieve a list of contacts', function(done) {
    supertest(app)
      .get('/v1/contacts')
      .set('Authorization', `Bearer ${authToken}`)
      .query({ page: 1, limit: 10 })
      .expect(200)
      .end((err, res) => {
        expect(res.body).to.be.an('object');
        expect(res.body.documents).to.be.an('array');
        randomeContact = res.body.documents[0];
        randomeContact_2 = res.body.documents[2];
        done();
      });
  });

  it('should retrieve a specific contact by ID', function(done) {
    const contactId = randomeContact._id;
    supertest(app)
      .get(`/v1/contacts/${contactId}`)
      .set('Authorization', `Bearer ${authToken}`)
      .expect(200)
      .end((err, res) => {
        expect(res.status).to.equal(200);
        expect(res.body).to.have.property('name').to.equal(randomeContact.name);
        expect(res.body).to.have.property('phoneNumber').to.equal(randomeContact.phoneNumber);
        expect(res.body).to.have.property('contactEmail').to.equal(randomeContact.contactEmail);
        done();
      });
  });

  it('should update a specific contact', function(done) {
    const contactId = randomeContact._id; 
    const updateData = {
      phoneNumber: "111-111-1111"
    };
    supertest(app)
      .patch(`/v1/contacts/${contactId}`)
      .set('Authorization', `Bearer ${authToken}`)
      .send(updateData)
      .expect(204)
      .end((err, res) => {
        expect(res.status).to.equal(204);
        supertest(app)
        .get(`/v1/contacts/${contactId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200)
        .end((err, res) => {
            expect(res.status).to.equal(200);
            expect(res.body).to.have.property('name').to.equal(randomeContact.name);
            expect(res.body).to.have.property('phoneNumber').to.equal(updateData.phoneNumber);
            expect(res.body).to.have.property('contactEmail').to.equal(randomeContact.contactEmail);
            done();
        });
      });
  });

  it('should delete a specific contact and confirm deletion', function(done) {
    const contactId = randomeContact_2._id; 
    supertest(app)
      .delete(`/v1/contacts/${contactId}`)
      .set('Authorization', `Bearer ${authToken}`)
      .expect(204)
      .end((err, res) => {
        if (err) return done(err);
        expect(res.status).to.equal(204);
  
        // Follow-up GET request to verify deletion
        supertest(app)
          .get(`/v1/contacts/${contactId}`)
          .set('Authorization', `Bearer ${authToken}`)
          .expect(404) // Expecting 'Not Found' status after deletion
          .end((error, response) => {
            if (error) return done(error);
            expect(response.status).to.equal(404);
            // console.log(response);
            expect(response.body.message).to.equal("Not found!");
            done();
          });
      });
  });
});



describe('GET /users', function() {
    it('should fail requesting this endpoint', function(done) {
        supertest(app)
        .get('/users')
        .expect('Content-Type', /json/)
        .expect(404)
        .end(function(err, response) {
            if (err) return done(err);
            expect(response.status).to.equal(404);
            expect(response.body.message).to.equal("Invalid Endpoint!");
            done();
        });
    });
});




/*
(async () => {
    const { expect } = await import('chai');  // Use dynamic import
    const request = (await import('supertest')).default;
    const app = (await import('../src/modules/app/app.module.js')).default;

    // Dummy auth token - Replace with valid token or mock authentication for tests
    
    const adminToken = 'valid-admin-token';
    const userToken = 'valid-user-token';

    describe('User Routes', function () {

        let createdUserEmail;

        // Test for creating a user (POST /v1/users)
        it('should create a new user (ADMIN only)', async function () {
            const newUser = {
                email: 'testuser@example.com',
                password: 'Password123!',
                role: 'USER',
                name: 'Test User'
            };

            const response = await request(app)
                .post('/v1/users')
                .set('Authorization', `Bearer ${adminToken}`)  // Set Authorization header
                .send(newUser);

            expect(response.status).to.equal(204);  // Expecting no content status
            createdUserEmail = newUser.email;
        });

        // Test for querying users (GET /v1/users)
        it('should get a list of users (ADMIN only)', async function () {
            const response = await request(app)
                .get('/v1/users')
                .set('Authorization', `Bearer ${adminToken}`)  // Set Authorization header
                .send();

            expect(response.status).to.equal(200);
            expect(response.body).to.be.an('array');
            expect(response.body[0]).to.have.property('email');
        });

        // Test for getting a specific user by email (GET /v1/users/:userEmail)
        it('should get a specific user by email (ADMIN only)', async function () {
            const response = await request(app)
                .get(`/v1/users/${createdUserEmail}`)
                .set('Authorization', `Bearer ${adminToken}`)
                .send();

            expect(response.status).to.equal(200);
            expect(response.body).to.have.property('email', createdUserEmail);
            expect(response.body).to.not.have.property('password');  // Ensure password is not included
        });

        // Test for updating a user's data (PATCH /v1/users/:userEmail)
        it('should update user information (ADMIN only)', async function () {
            const updatedData = { name: 'Updated Test User' };

            const response = await request(app)
                .patch(`/v1/users/${createdUserEmail}`)
                .set('Authorization', `Bearer ${adminToken}`)
                .send(updatedData);

            expect(response.status).to.equal(200);
            expect(response.body).to.have.property('email', createdUserEmail);
        });

        // Test for deleting a user (DELETE /v1/users/:userEmail)
        it('should delete a user (ADMIN only)', async function () {
            const response = await request(app)
                .delete(`/v1/users/${createdUserEmail}`)
                .set('Authorization', `Bearer ${adminToken}`)
                .send();

            expect(response.status).to.equal(204);  // Expecting no content
        });

        // Test for user reset password (PUT /v1/users/:userEmail)
        it('should reset user password (ADMIN only)', async function () {
            const passwordData = {
                currentPassword: 'Password123!',
                newPassword: 'NewPassword456!'
            };

            const response = await request(app)
                .put(`/v1/users/${createdUserEmail}`)
                .set('Authorization', `Bearer ${adminToken}`)
                .send(passwordData);

            expect(response.status).to.equal(204);  // Expecting no content
        });
    });
})();

*/