const errorCode = {
  INVALID_ENDPOINT: 'INVALID_ENDPOINT',
  USER_ROLE_LOGIN: 'USER_ROLE_LOGIN',
  UNVERIFIED_EMAIL: 'UNVERIFIED_EMAIL',
  ADMIN_ROLE_LOGIN: 'ADMIN_ROLE_LOGIN',
  VERIFIED_EMAIL: 'VERIFIED_EMAIL',
  ADMIN_REGISTER_USER: 'ADMIN_REGISTER_USER',
  ADMIN_REGISTER_ADMIN: 'ADMIN_REGISTER_ADMIN',
  ADMIN_GET_USERS: 'ADMIN_GET_USERS',
  ADMIN_GET_USER: 'ADMIN_GET_USERS',
  ADMIN_GET_EDITOR: 'ADMIN_GET_EDITOR',
  ADMIN_UPDATE_USER: 'ADMIN_UPDATE_USER',
  ADMIN_UPDATE_EDITOR: 'ADMIN_UPDATE_EDITOR',
  ADMIN_DELETE_USER: 'ADMIN_DELETE_USER',
  ADMIN_DELETE_HIMSELF: 'ADMIN_DELETE_HIMSELF',
  ADMIN_DELETE_EDITOR: 'ADMIN_DELETE_EDITOR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  UNREGISTERED_EMAIL: 'UNREGISTERED_EMAIL',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_CODE: 'INVALID_CODE',
  NOT_FOUND: 'NOT_FOUND',
  TAKEN_EMAIL: 'TAKEN_EMAIL',
  REGISTRATION_SUBJECT: 'REGISTRATION_SUBJECT',
  RESET_SUBJECT: 'RESET_SUBJECT'
}

module.exports = errorCode
