name: Run tests

on:
  pull_request:
    branches: ['main', 'back-end', 'adding_tests_backend']
  push:
    branches: ['main', 'adding_tests_backend']

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          
      - name: Install Dependencies
        run: cd backend && npm ci
      - name: Run tests
        run: cd backend && npm test
        