name: Run tests

on:
  pull_request:
    branches: ['main', 'back-end', 'adding_tests_backend']
  push:
    branches: ['main', 'adding_tests_backend']

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest        # Docker image for Redis
        ports:
          - 6379:6379             # Expose Redis on port 6379
        options: --health-cmd "redis-server --version" --health-interval 5s --health-timeout 5s --health-retries 3

    env:
      TZ: ${{ secrets.TZ }}
      PORT: 3000
      NODE_ENV: development
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET}}
      JWT_ACCESS_EXPIRATION_HOURS: ${{ secrets.JWT_ACCESS_EXPIRATION_HOURS}}
      JWT_REFRESH_EXPIRATION_MONTHS: ${{ secrets.JWT_REFRESH_EXPIRATION_MONTHS}}
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD}}

    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Install Dependencies
        run: cd backend && npm i
      - name: Run tests
        run: cd backend && npm test
      
      - name: Final step (marking success or failure)
        if: success()
        run: echo "Tests passed. Workflow completed successfully!"
        